### PR TITLE
Serializing DateTimeOffset objects with ISO8601

### PR DESCRIPTION
**Pull request by StanleyGoldman**
Fixes: #447

Cache objects were being serialized with their date times just being `ToString`d.
This works fine most of the time, but of course it is not consistent.

### CODE REVIEW

**Comment by sguthals** [comment]
You also removed using Octokit in this PR. Any reason for that?

**Comment by StanleyGoldman** [comment]
@jcansdale That does not enforce the ISO8601 format. From what I understand if you do not set a format you end up with your system global format. Which in the case of some users, like @shana, who prefer a 24-Hour time format, this leads to an output that is not among the formats that are parsed for by default.

**Comment by StanleyGoldman** [comment]
@sguthals It was not intentional. I think Resharper removed it, but the namespace was not used so it's a null change.

**Comment by sguthals** [comment]
Looks good!

**Pull request merged**
