### PR TITLE
Changing UpdateRepositoryInfo to ClearRepositoryInfo

### PR DESCRIPTION
**Pull request by StanleyGoldman**
As mentioned here https://github.com/github-for-unity/Unity/pull/390#issuecomment-342514069

https://github.com/github-for-unity/Unity/blob/88c114e5ac64496dca8b8383905192aaed143f81/src/GitHub.Api/Git/Repository.cs#L590-L629

`Name` and `CloneUrl` are already calculated lazily. The functionality in `UpdateRepositoryInfo` is a duplicate of that lazy load. So it would be best to remove `UpdateRepositoryInfo` and add `ClearRepositoryInfo` which just clears the values and then lets the lazy load kick in.

### CODE REVIEW

**Comment by sguthals** [comment]
So CurrentRemote is guaranteed to not be null now?

**Comment by StanleyGoldman** [comment]
@sguthals good catch. I meant to clear those values instead.
As the property getter code will populate those values when null.

https://github.com/github-for-unity/Unity/blob/88c114e5ac64496dca8b8383905192aaed143f81/src/GitHub.Api/Git/Repository.cs#L590-L629

**Comment by sguthals** [comment]
Can you add more of a description? Why are we doing this?

**Comment by StanleyGoldman** [comment]
@sguthals Feel free to just reject the pull request next time.
I added more detail.

**Comment by sguthals** [comment]
@StanleyGoldman - sounds good. This is a great description. Looks all good to me!

**Pull request merged**
