### PR TITLE
Add test scripts and documentation

### PR DESCRIPTION
**Pull request by meaghanlewis**
Working on simple scripts to run the tests on both Mac and Windows. Also added a `how-to-test` doc to describe the tests and how to run them.

I haven't scripted much, so feedback is appreciated!

### CODE REVIEW

**Comment by StanleyGoldman** [comment]
I just tried this out on Windows. so far it seems to be working well..

My first thought is, since `./build.sh` and `build.cmd` both build in Debug by default.
Maybe `./test.sh` and `test.cmd` should both test in Debug by default as well.

**Comment by meaghanlewis** [comment]
Thanks for the feedback @StanleyGoldman, so to test in Debug by default I can just set the configuration to Debug, right?

**Comment by meaghanlewis** [comment]
thanks for your changes @StanleyGoldman 

Adding some observations about running the tests on mac.

running `./test.sh` results in:
`packages\NUnit.Runners.2.6.4\tools\nunit-console.exe: command not found`

when i try to run the nunit-console with mono (ex. `mono packages/NUnit.Runners.2.6.4/tools/nunit-console.exe`), it starts successfully

but when i  run any tests (ex. `mono packages/NUnit.Runners.2.6.4/tools/nunit-console.exe "build/IntegrationTests/IntegrationTests.dll"`) all the tests fail immediately and I see a lot of messages similar to this: 
Method `IntegrationTests.BaseIntegrationTest:TestFixtureSetUp ()' is inaccessible from method `GitHub.Unity.Guard:set_InUnitTestRunner

screen shot 2017-11-07 at 1 25 17 pm

**Comment by StanleyGoldman** [comment]
So I have no idea yet how to make this run in mono, but I'm happy enough having it work on windows for now. I'm going to merge this in and add an issue for it.

**Comment by meaghanlewis** [comment]
Thanks @StanleyGoldman for merging this and creating the test.sh issue 🎉

**Pull request merged**
