### PR TITLE
Cleanup in ApplicationCache

### PR DESCRIPTION
**Pull request by StanleyGoldman**
As mentioned in https://github.com/github-for-unity/Unity/pull/390#issuecomment-342515942
I changed `IRemoteConfigBranchDictionary` to implement `IDictionary<string,Dictionary<string,ConfigBranch>>`

### CODE REVIEW

**Comment by StanleyGoldman** [comment]
`IRemoteConfigBranchDictionary` should have never implemented `IDictionary<string, IDictionary<string, ConfigBranch>>`. Fixing that allowed me to remove a chunk of unused code.

`RemoteConfigBranchDictionary` inherits `Dictionary<string, Dictionary<string, ConfigBranch>>` as a result it automatically implements `IDictionary<string, Dictionary<string, ConfigBranch>>` which is not the same as `IDictionary<string, IDictionary<string, ConfigBranch>>`.

**Comment by shana** [comment]
Also, in general we don’t have any custom implementations of IDictionary and other list/collection interfaces, so there’s no advantage in passing interfaces around (tests can use the concrete classes just fine as well)

Unrelated to Dictionary, just fyi Unity can serialize `List<T>` so we tend to rely on concrete classes for these things.

**Comment by StanleyGoldman** [comment]
`RemoteConfigBranchDictionary` has functionality that is specific to Unity (i.e. runs in Mono).
Our unit tests cannot use classes that make reference to Unity's libraries. So those classes are usually represented with interfaces and stubbed in unit tests to make other classes testable.

To aid this effort classes in `GitHub.Api` in particular don't reference the Unity libraries.

**Comment by StanleyGoldman** [comment]
`IRemoteConfigBranchDictionary` lives in `GitHub.Api`

**Pull request merged**
