### PR TITLE
Unit tests that show Tree control maintains checked/collapsed state

### PR DESCRIPTION
**Pull request by StanleyGoldman**
- Adding tests to prove that the load function
  - Loads with collapsed nodes as expected
  - Loads with selected nodes as expected

### CODE REVIEW

**Comment by StanleyGoldman** [comment]
So after my first foray into this, I'm able to reproduce the bug, I see that the load functionality works as expected. I suspect there is a serialization issue, but everything is the same as checked state.

**Comment by Lobsterovich** [comment]
5+

**Comment by Lobsterovich** [comment]
5+

**Comment by shana** [comment]
There's a bug somewhere, but it's really hard to track down. I got it a couple of times, but it's not consistently reproducible.

collapsed-tree

**Comment by StanleyGoldman** [comment]
Cool, i changed the labels on the bug.

**Comment by StanleyGoldman** [comment]
@shana I think after #698 this bug is resolved. See if you can reproduce it.

**Comment by StanleyGoldman** [comment]
i'm pretty sure it happens every other domain reload

**Comment by StanleyGoldman** [comment]
but data that is created after the first domain reload, is persisted after the second domain reload

**Comment by StanleyGoldman** [comment]
touching the file system twice and focusing unity once, which is one domain reload, as i understand it, also reproduces the issue

**Pull request closed without merging**
