### PR TITLE
Fixing #351

### LINKED ISSUE #351: NullReferenceException: Object reference not set to an instance of an object
### Prerequisites

- Be sure to run with tracing enabled to capture runtime details in the log file
- Include the log file in the PR.
  - On Windows, the extension log file is at `%LOCALAPPDATA%\GitHubUnity\github-unity.log`
  - On macOS, the extension log file is at `~/Library/Application Support/GitHubUnity/github-unity.log`

### Description

Right after installing the extenstion, and opening the Github Window the console is spammed with errors and the window is blank. The settings window works tho.

### Steps to Reproduce

1. [First Step]
Install Github for Unity
2. [Second Step]
Open the Github Window
3. [and so on...]
Look at console

**Expected behavior:** [What you expect to happen]
For the window to show up with no errors
**Actual behavior:** [What actually happens]
The window is blank and there are errors
**Reproduces how often:** [What percentage of the time does it reproduce?]
100% of the time
### Additional Information
I have Unity 2017.2.0b5 (64-bit) and the latest Github for Unity release.
Any additional information, configuration or data that might be necessary to reproduce the issue.
[github-unity.log](https://github.com/github-for-unity/Unity/files/1368670/github-unity.log)

### PR DESCRIPTION
**Pull request by GalHorowitz**
Applying shiena's code fixes #351.

### Description of the Change

> the problem is that ImageConversion got moved out to a separate DLL, which means using Texture2D as a DLL location base no longer works. Worse, it got moved to its own assembly - literally a DLL which only contains this class, which means there is no type we can use to get at its location. So, sigh, we'll need to add yet another codepath to the StreamExtensions code to reference the UnityEngine.ImageConversionModule.dll dll and get the ImageConversion type.

Apparently, you don't need to, and that's all you have to do. 

### Benefits

Solving #351

### CODE REVIEW

**Comment by StanleyGoldman** [comment]
Hey @GalHorowitz thanks for participating and trying to fix this issue.
We can definitely use the help!

Did you test this in other versions of unity yet?
I have to go download the new version of Unity now...

**Comment by GalHorowitz** [comment]
This was tested in the latest Unity beta. I will be able to test Unity 5.x later on today.

**Comment by GalHorowitz** [comment]
I just realized Unity 2017.2 is no longer in Beta, it is the official release. 2017.3 is the Beta. Should I still verify Unity 5.x?

**Comment by StanleyGoldman** [comment]
Hey @GalHorowitz,
Currently we support Unity 5.4 to 2017.1
I will be testing in a few different versions of Unity, but if you could check at least one for us that would be great. If not that's okay too, I'll let you know what I find when i get a chance..

**Comment by GalHorowitz** [comment]
I tested it on the following versions:

- 2017.2.0b5
- 2017.1.0f3
- 5.6.4f1

I did not encounter any issues in either.

**Comment by GalHorowitz** [comment]
@StanleyGoldman Is there any other version I should test?

**Comment by StanleyGoldman** [comment]
Hey @GalHorowitz 

No it's okay, you've done great so far.
I haven't gotten a chance to do my tests yet, I will today.

**Comment by StanleyGoldman** [comment]
Okay, I'm actually testing now...
Checking the following versions..

- [ ] Unity 5.4.5f1 (64-bit)
- [ ] Unity 5.5.3f1 (64-bit)
- [ ] Unity 5.6.0f3 (64-bit)
- [ ] Unity 2017.1.0f3 (64-bit)
- [ ] Unity 2017.2.0f3 (64-bit)

**Comment by StanleyGoldman** [comment]
Yea, this checks out...

**Comment by shana** [comment]
I've added some extra logic to ensure that when Unity eventually gets rid of the full UnityEngine.dll, we still work correctly and don't have to worry about this again.

**Pull request merged**
