### PR TITLE
Fix GitHub sign in with a browser

### PR DESCRIPTION
**Pull request by chantzish**
As of September 8 2021 github removed API authentication through query parameters - https://developer.github.com/changes/2020-02-10-deprecating-auth-through-query-param/

### Requirements

* Filling out the template is required. Any pull request that does not include enough information to be reviewed in a timely manner may be closed at the maintainers' discretion.
* All new code requires tests to ensure against regressions

### Description of the Change
As of September 8 2021 github removed API authentication through query parameters - https://developer.github.com/changes/2020-02-10-deprecating-auth-through-query-param/ .
Changing to auth via "Authorization: token ..." header.

### CODE REVIEW

**Review by LukasKristensen — APPROVED** [review]

**Review by dan-i-am — APPROVED** [review]
Change worked for me

**Comment by MeirArani** [comment]
I just had to dig through several issue threads and find the instructions on how to apply this fix myself. 

It's been over half a year and this basic functionality is _still_ busted. Please fix this already.

**Comment by naim** [comment]
Can we get this merged and a patch release cut?

**Review by Nightcaat — APPROVED** [review]
This should be merged, I know this repository has been deprecated but it worked perfectly

**Review by harshitverma209 — APPROVED** [review]

**Comment by ChrisMenning** [comment]
I can confirm that this bug is still present, and this fix works. Please merge.

**Comment by Shain-Allen** [comment]
I can also confirm that this bug is still present and that applying this fixes it

**Pull request closed without merging**
