### PR TITLE
Support git-worktree on History

### PR DESCRIPTION
**Pull request by shiena**
#865 You can display the history when opening working directory made with `git-worktree`.

### CODE REVIEW

**Comment by StanleyGoldman** [comment]
Hey @shiena thanks for this, really. It's going to require a fair bit of testing to make sure it's right.

Here is the first things I tested.
1. I created a brand new project, initialized git with GitHub for Unity.
1. Performed a few commits and created a branch.
1. Opened the command line & created a worktree pointing to the other branch.
1. I opened up a second instance of Unity in the worktree path.
1. I performed a few commits. I felt like the after-commit refresh was a bit slow to realize.
1. Then I published from the worktree instance of Unity.
   1. The main instance of Unity recognized the new remote and refreshed accordingly.
   1. The worktree instance of Unity did not.

I'm gonna dig around for a bit, see if I can figure it out.

**Comment by StanleyGoldman** [comment]
Ok, your patch is definitely pretty crafty and I think i figured out the issue.

The `RepositoryWatcher` is correctly watching the worktree's working directory, but we are going to need to spawn a second `RepositoryWatcher` to watch the git folder of the main folder's `.git` directory.

**Comment by StanleyGoldman** [comment]
Hey @shiena just pushed some code to your branch. Wanna test it out for me.
It finishes what you started with the worktree functionality.

**Comment by shiena** [comment]
@StanleyGoldman Thank you for improving worktree support.
As RepositoryWatcher improved, it was reflected in the branch tab when changing the branch.
This is great!

**Pull request merged**
